### ISSUE TITLE
配置https

### ISSUE THREAD

**Issue by yfhuang521** [CybexDex/cybex-web-2.0#1]
你好，请问如何配置https呢？

**Comment by Summerdx** [comment]
如果是指网关或者相关接口的配置，都在 `client/lib/config` 目录下 
根据不同环境修改对应的config文件即可

**Comment by yfhuang521** [comment]
@Summerdx 就是想搭建一个https的服务

**Comment by Summerdx** [comment]
@yfhuang521 这个库只是web 2.0的UI前端开源，并不包括相关服务。

欢迎提交使用过程中发现的bug或者UI层的feature request。
